#!/bin/bash

function find_broken_symlinks()
{
    PREFIX="$(dirname "$1")"
    if [[ "$PREFIX" = / ]]
    then
        PREFIX=""
    fi
    if [[ -n "$(basename "$1")" ]]
    then
        PREFIX="$PREFIX/$(basename "$1")"
    fi
    for file in "$PREFIX"/*
    do
        if [[ -L "$file" && !(-e "$file") ]]
        then
            echo "$file"
        else
            if [[ !(-L "$file") && -d "$file" ]]
            then
                find_broken_symlinks "$file"
            fi
        fi
    done
}

for dir in "$@" 
do
    find_broken_symlinks "$dir"
done
