#!/bin/bash

for file in "$@"
do
    if [[ -e "$file" ]]
    then
        echo "$file"
        read new_name
        dir="$(dirname "$file")"
        if [[ -n "$new_name" && !(-e "$dir/$new_name") ]]
        then
            mv "$file" "$dir/$new_name"
        fi
    fi
done
