#!/bin/bash

dir="/tmp"
if [[ !(-d "dir") ]]
then
    mkdir "$dir"
fi 

prev="$dir/watchthis_prev.txt"
cur="$dir/watchthis_cur.txt"

period="$1"
shift

"$@" > "$prev"
echo -n "" > "$cur"
cat "$prev"
diff -u "$cur" "$prev"
echo -e "\n"

while true
do
    sleep "$period"
    "$@" > "$cur"
    cat "$cur"
    diff -u "$prev" "$cur"
    cat "$cur" > "$prev"
    echo -e "\n"
done
